create a pull request
Khaled-AlKhateeb/YouFlex pull request #35
Opened 2022-10-21 16:40 UTC by Khaled-AlKhateeb

YOUFLEX, capstone 🎥 :
This capstone project is developed by @inspecta and @Khaled-AlKhateeb.
Fetched shows from TV Maze API.
Displayed the shows dynamically using JavaScript.
Add likes to shows using involvement API.
Add popup window for the shows details.
Add comments section in the popup window that POST to the involvement API.
Fetch back the comments for each show and display them in the comment section.
Created 2 functions to count both likes and comments that are displayed.
Added JEST dependency.
Tested the count functions using JEST.

for more info about the project please see this [Zoom Video](https://drive.google.com/file/d/1CCYwOdMWnkQn97ZDO8wmf0f5MQBrVhFj/view?usp=sharing).

2022-10-21 16:48 UTC, Abenezer-Tilahun reviewed
Hello @Khaled-AlKhateeb  👋 ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

✖️ Invalid Code Review Request ✖️

You have submitted a project, that has failing linters. Kindly ensure that you fix the failing linter errors then request for a review in your dashboard.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Khaled-AlKhateeb  in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2022-10-21 17:11 UTC, zainsadaqat requested changes
# Required Changes 🔁
# Hello TEAM! 😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of GitHub Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [x] On Cards, Please show the number of comments as well as showing the number of likes 👍🏻 
<img width="1302" alt="Screenshot 2022-10-21 at 10 10 10 PM" src="https://user-images.githubusercontent.com/83048208/197251281-ee7e77e5-10d5-41e9-981e-bce17506c508.png">


_Check the comments under the review._


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-22 12:26 UTC, christianbiring1 requested changes
Hi @Khaled-AlKhateeb @inspecta , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
# REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/197338834-6abb83fd-dc12-41ed-8163-50f3b4cca7f2.gif)

 ## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR summary
- [ ] Good commit message

 ## Required Changes ♻️
- [ ] As said by the previous review, Kindly make sure When a user clicks on the Like button of an item, the interaction should get recorded in the [Involvement API](https://www.notion.so/Involvement-API-869e60b5ad104603aa6db59e08150270), and the screen gets updated. no need to refresh the page to get the actual number of `likes`
- [ ] The same applies to the comments on the popup.
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-22 12:26 UTC, christianbiring1 commented on src/modules/comments-counter.js
> +    // eslint-disable-next-line no-await-in-loop
[OPTIONAL] 
-[ ] Kindly make sure you are not disabling some rules for the linters make sure your code keeps the standards

2022-10-22 15:44 UTC, sumairq approved these changes
### Hi Team, 

<img src="https://media2.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-10-22 15:46 UTC, merged

2022-10-22 16:03 UTC, inspecta commented
Thanks @sumairq